name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install -y clang mold

      - name: Modify dependencies
        run: |
          sed -i '/bevy = {/,/features = \[/,/\]/ {/"dynamic_linking"/d; /"file_watcher"/d}' Cargo.toml
          sed -i 's/#log = { version = ".*", features = .*}/log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }/' Cargo.toml

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Modify dependencies
        shell: pwsh
        run: |
          $content = Get-Content Cargo.toml -Raw
          $content = $content -replace '("dynamic_linking",\s*|"file_watcher",\s*)', ''
          $content | Set-Content Cargo.toml
          (Get-Content Cargo.toml) -replace '#log = @{ version = "\*"; features = \["max_level_debug", "release_max_level_warn"\] }', 'log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }' | Set-Content Cargo.toml

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-pc-windows-msvc
          override: true

      - name: Build
        run: cargo build --verbose --release --target x86_64-pc-windows-msvc

  arm-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: cargo install cross

      - name: Modify dependencies
        run: |
          sed -i '/bevy = {/,/features = \[/,/\]/ {/"dynamic_linking"/d; /"file_watcher"/d}' Cargo.toml
          sed -i 's/#log = { version = ".*", features = .*}/log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }/' Cargo.toml

      - name: Build
        run: cross build --verbose --release --target armv7-unknown-linux-gnueabihf
